name: Check Changelog

on:
  push:
    tags:
      - "*"
    branches:
      - "*"

jobs:
  changelog:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}
      IS_TAG_PUSH: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    defaults:
      run:
        working-directory: ./src/py/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Changelog
        id: changelog
        uses: geopozo/changelogtxt-parser
        with:
          working-directory: ./src/py/
          tag-check: ${{ env.IS_TAG_PUSH == 'true' && env.TAG || '' }}
